ホーム・トークルーム一覧・トークルーム作成
stamp-team/chat-flutter pull request #12
Opened 2020-06-13 06:26 UTC by thoth000

# 担当したissue
#5 #8 

# 作成画面の見た目
（作成画面は自分が用意した中の最小デバイスでもレイアウトは問題なかったです）
**device** : Pixel 3 (Androidなので iOSと多少差はありますが、大きな違いはないと思います。)
<img width="250px" src="https://user-images.githubusercontent.com/51738889/84561661-4d772480-ad89-11ea-808a-483adfd03d9c.png"> <img width="250px" src="https://user-images.githubusercontent.com/51738889/84561693-8ca57580-ad89-11ea-8337-93d40bf6236b.png"> <img width="250px" src="https://user-images.githubusercontent.com/51738889/84561716-b65e9c80-ad89-11ea-88e8-78bad35d03f6.png">

# 注意点
main.dartを変更してありますが、ページ遷移の変更と無駄なコメント削除のみなのでmainは見なくても大丈夫かなと思います。

分からないところがあれば、コメントを随時入れていこうかなと思います。

2020-06-13 08:22 UTC, thoth000 commented
すいません！
もっと簡単にかけることに気付きました😝
レビューはまだ大丈夫です！🙏🙏🙏

2020-06-13 13:16 UTC, thoth000 commented
コードレビューお願いします！

2020-06-14 04:49 UTC, PictoMki requested changes
一応レビューしました。
相談が必要そうな部分があるので別途相談しましょう！

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/home.dart
> +  @override
レビュー基準がないので、なんともいえないのですが
クラス名とファイル名は揃えて欲しいです。
今回のケースだと
HomePageの方はいいと思うので、ファイル名はhome_page.dartの方が自然だと思います。

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/home.dart
> +) {
widget名が少し曖昧なので、widget名でそのwidgetが何かわかる名前にして欲しいです。
例えば、MeListItemとか？

あと個人的に切り分けられるWidgetはファイルを分けていきたい(開発方針決める必要あり)ので
StatelessWidgetにして、ファイルを分けて欲しいです。

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/home.dart
> +  return Column(
ここもme()の部分と同様

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/home.dart
> +) {
ここもme()同様命名をわかりやすくして欲しいです！

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/home.dart
> +              overflow: TextOverflow.ellipsis,
ここ文字サイズと画像サイズくらいの違いなら
itemのwidgetで共通化した方がいいかも。
itemにbool isMeとかのフラグを渡してあげて・・。

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/main.dart
>    }
initialRouteとrouteの設定をして各ページの導線を作って欲しい

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/mainpage.dart
> +import 'package:flutter/material.dart';
ファイル名をmain_pageとして欲しい！
命名規則はこちら参照
https://qiita.com/mkosuke/items/42c19d7edbf111f7fb71

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/mainpage.dart
> +  return AppBar(
ここタイポしてる！
`talkAppBat`→`talkAppBar`

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/room.dart
> +  bool isRead,
myMessageとfriendMessageも共通化したい
messageItemとかにして、isMeフラグで変更部分変更した方が良さそう。(要相談)

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/room.dart
> +  final String name;
ファイル名をroom_pageに変更で！

2020-06-14 04:49 UTC, tomoki-inoue1221 commented on lib/talk.dart
> +  @override
ファイル名をtalk_pageに変更で！

2020-06-14 04:52 UTC, tomoki-inoue1221 commented on lib/home.dart
> +  return Column(
ここもme()同様だ！忘れてた！

2020-06-14 04:53 UTC, tomoki-inoue1221 commented
roomとかmessageとかモデル作りたいけど、一旦いいですかね？

2020-06-14 05:21 UTC, thoth000 commented on lib/home.dart
> +  @override
クラス名とファイル名を揃える件、了解です！

2020-06-14 05:39 UTC, thoth000 commented on lib/main.dart
>    }
分からないので学習します！🚀

2020-06-14 06:59 UTC, thoth000 commented
こちらを閉じて、新しいブランチで作成したPull Requestを出します！

2020-06-14 06:59 UTC, closed without merging