ホーム・トークルーム一覧・トークルーム画面の作成（再）
stamp-team/chat-flutter pull request #13
Opened 2020-06-14 07:01 UTC by thoth000

# 担当したissue
#5 #8 

# 作成画面の見た目
（作成画面は自分が用意した中の最小デバイスでもレイアウトは問題なかったです）
**device** : Pixel 3 (Androidなので iOSと多少差はありますが、大きな違いはないと思います。)
<img width="250px" src="https://user-images.githubusercontent.com/51738889/84561661-4d772480-ad89-11ea-808a-483adfd03d9c.png"> <img width="250px" src="https://user-images.githubusercontent.com/51738889/84561693-8ca57580-ad89-11ea-8337-93d40bf6236b.png"> <img width="250px" src="https://user-images.githubusercontent.com/51738889/84561716-b65e9c80-ad89-11ea-88e8-78bad35d03f6.png">

2020-06-14 07:55 UTC, PictoMki requested changes
先ほど電話で話した件コメントしました！
漏れてたらすみません・・。

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/talk_page.dart
> +) {
ここもStatelessWidgetがいいです！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/room_page.dart
> +) {
ここもStatelessWidgetがいい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page_tile_group.dart
> +            info[2],
model使わないとここの可読性が低くなってしまうので、
model作りましょう！
お時間ある時に少し説明します！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page.dart
> +        false,
ここGroupモデルを作りましょう！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page.dart
> +      ],
ここユーザーモデル作りましょう！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/main_page.dart
> +    elevation: 1.0,
ここもStatelessがいい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/main_page.dart
> +  return AppBar(
ここもStatelessがいい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/room_page.dart
> +) {
あといけそうだったらMesssgeモデルを作ってそれを渡すようにして欲しい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/talk_page.dart
> +        ),
Roomモデルを作って渡すようにして欲しい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page_tile_group.dart
> +          ),
配列の時は配列.forEachにするとみやすい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page.dart
> +      ],
Groupモデルを作成してGroupを渡すようにして欲しい！

2020-06-14 07:55 UTC, tomoki-inoue1221 commented on lib/home_page.dart
> +      ],
Userモデルを作成して、Userを渡すようにして欲しい！

2020-06-14 08:11 UTC, thoth000 commented on lib/home_page_tile_group.dart
> +          ),
早速すいません！
forEachのWidgetの返し方が分かりません！😢

2020-06-14 08:57 UTC, 1amageek commented
Model定義待ちですね。

Interfaceだけでも定義しておくと全然扱いが楽だと思います。

2020-06-14 13:24 UTC, tomoki-inoue1221 commented
レビューだと表現しきれない部分があったので、僕だったらこうするかなという実装をこちらにしています。
こちらdiffの確認用なので、マージはしないでください！

ソースにコメント残してるので確認お願いします！
https://github.com/thoth000/chat-flutter/pull/1

2020-06-15 13:34 UTC, thoth000 commented
グループと友達のリストだけなら、わざわざstatelessWidgetで用意する必要ないですか？

2020-06-16 05:48 UTC, tomoki-inoue1221 commented
> グループと友達一覧のふたつのリストだけなら、わざわざstatelessWidgetで用意する必要ないですか？🐲

どのStatekessWidgetのな話ですか？

コメントにも確か残していますが、特に意味はないです。

2020-06-16 10:27 UTC, tomoki-inoue1221 commented on lib/main_page.dart
> +    setState(
ここがキャメルケースになってないので、
changePageにしてください！

2020-06-16 10:28 UTC, tomoki-inoue1221 commented
flutter format .コマンドは実行してますか？
実行したらコード変わってしまうので、changePageを修正後再度実行してプッシュをお願いします！

2020-06-16 11:04 UTC, tomoki-inoue1221 commented
いい感じだと思います！

2020-06-16 11:50 UTC, 1amageek commented
マージン、フォントサイズあたりがハードコードされてますね。

早めにどこかに定義した方が良さそうです。

2020-06-16 12:17 UTC, tomoki-inoue1221 commented
@1amageek 
レビューありがとうございます!
ログイン・新規登録画面もハードコードされてるので、共通化処理を別のissueで切っているので
こちら一旦マージさせていただいてもよろしいですか？
https://github.com/stamp-team/chat-flutter/issues/14

2020-06-16 12:56 UTC, 1amageek approved these changes

2020-06-16 12:56 UTC, merged